### ISSUE TITLE
xcodebuild error against arch i386 (Bugsnag 5.1.0, Cordova 5.3.3 iOS 3.9.2)

### ISSUE THREAD

**Issue by allenbriggs** [bugsnag/bugsnag-cocoa#102]
I am having build errors with the latest iteration of **Bugsnag 5.1.0**.  A little background on my setup: I'm using **Cordova 5.3.3 (iOS 3.9.2 platform)**.  I get the following error when running ``cordova build`` from the terminal (I was able to get this error in Xcode when switching ``Target > Build Settings > Build Active Architecture Only > Debug = YES``) :

```
The following build commands failed:
	Ld /Users/myself/desktop/my-app/my-app.app normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/myself/desktop/my-app/cordova/platforms/ios/cordova/build-debug.xcconfig,-project,my-app.xcodeproj,ARCHS=i386,-target,my-app,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/myself/desktop/my-app/cordova/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/myself/desktop/my-app/cordova/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/myself/desktop/my-app/cordova/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/myself/desktop/my-app/cordova/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1016:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
```

Let me know if you have any questions, any advice would be greatly appreciated!

**Comment by kattrali** [comment]
Thank you for the report, @allenbriggs. Is it possible that the app is being built for an iOS version before 6.0? Bugsnag supports iOS 6.0+. I'd also recommend trying:

1. Cleaning the project
2. Upgrading Node
3. Removing and re-adding the `ios` platform also sometimes seems to work

Failing those, could you provide some additional information, such as your Xcode and ios-sim versions? Thanks!

**Comment by kattrali** [comment]
Closing this issue for inactivity, feel free to reopen if there is any new information.
