### ISSUE TITLE
Address Sanitizer traps on Bugsnag SDK at app startup

### ISSUE THREAD

**Issue by jbelkins** [bugsnag/bugsnag-cocoa#1054]
### Describe the bug
I was running Address Sanitizer on a 64-bit iOS device attached to Xcode to locate a memory corruption issue in my app.

On app startup, during `application:didFinishLaunchingWithOptions:`, the Address Sanitizer traps on a call internal to Bugsnag (looks like the `is_jailbroken` C function.)  When I disable Bugsnag (by not calling `Bugsnag.start(...)`) the app starts and runs as expected.

Not sure if this is a legitimate bug on your part, but it would be nice to run Address Sanitizer without having to disable app services

### Steps to reproduce
Open a project with the Bugsnag SDK integrated
On your scheme's Run action, set "Address Sanitizer", "Detect use of stack after return", "Undefined Behavior Sanitizer", "Main Thread Checker", "Malloc Scribble", and "Zombie Objects" to checked
Select an attached iOS device as run destination
Press Run in Xcode

Expected: App starts and runs
Actual: Address Sanitizer stops app due to the following (logs are partial, DM me if you want full logs):
```
AppName(5442,0x104d4f880) malloc: enabling scribbling to detect mods to free blocks
=================================================================
==5442==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x0001703000de at pc 0x000104daceac bp 0x00016ce805f0 sp 0x00016ce7fd80
READ of size 22 at 0x0001703000de thread T0
    #0 0x104dacea8 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long)+0x118 (/private/var/containers/Bundle/Application/388679A6-0258-46EC-AC4C-E9927741A77D/AppName.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x18ea8)
    #1 0x104dad2bc in wrap_memcmp+0x84 (/private/var/containers/Bundle/Application/388679A6-0258-46EC-AC4C-E9927741A77D/AppName.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x192bc)
    #2 0x103ad67a0 in bsg_local_is_insert_libraries_env_var+0x160 (/private/var/containers/Bundle/Application/388679A6-0258-46EC-AC4C-E9927741A77D/AppName.app/AppName:arm64+0x100b5e7a0)
    #3 0x103ad6358 in is_jailbroken+0x694 (/private/var/containers/Bundle/Application/388679A6-0258-46EC-AC4C-E9927741A77D/AppName.app/AppName:arm64+0x100b5e358)
    #4 0x103ad0f20 in +[BSG_KSSystemInfo isJailbroken]+0x28 (/private/var/containers/Bundle/Application/388679A6-0258-46EC-AC4C-E9927741A77D/AppName.app/AppName:arm64+0x100b58f20)
    #5 0x103ad2980 in +[BSG_KSSystemInfo systemInfo]+0x1110 (/private/var/containers/Bundle/Application/388679A6-0258-46EC-AC4C-E9927741A77D/AppName.app/AppName:arm64+0x100b5a980)
    #6 0x103a51a78 in initCurrentState+0x3dc (/private/var/containers/Bundle/Application/388679A6-0258-46EC-AC4C-E9927741A77D/AppName.app/AppName:arm64+0x100ad9a78)
    #7 0x103a4f820 in -[BugsnagSystemState initWithConfiguration:]+0x7e0 (/private/var/containers/Bundle/Application/388679A6-0258-46EC-AC4C-E9927741A77D/AppName.app/AppName:arm64+0x100ad7820)
    #8 0x103a5a008 in -[BugsnagClient initWithConfiguration:]+0xc9c (/private/var/containers/Bundle/Application/388679A6-0258-46EC-AC4C-E9927741A77D/AppName.app/AppName:arm64+0x100ae2008)
    #9 0x103a3dd44 in +[Bugsnag startWithConfiguration:]+0x268 (/private/var/containers/Bundle/Application/388679A6-0258-46EC-AC4C-E9927741A77D/AppName.app/AppName:arm64+0x100ac5d44)
```

### Environment
* Bugsnag version: 6.7.1, installed with SPM
* CocoaPods version: not used
* Carthage version (if any): not used
* iOS/tvOS/macOS version(s): iOS 14.4.1, Xcode running on macOS 11.2.3
* Simulator or physical device: Physical device (iPad 6th Gen)
* Xcode version: 12.4
* Swift version (if applicable): 5.3.2

**Comment by jbelkins** [comment]
After talking with Bugsnag support, I updated to Bugsnag SDK version 6.8.1, and the problem resolved.  Closing.
